# Nome da aplicação
spring.application.name=findpark

# Conexão com o MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/findpark

# Segredo JWT
api.security.token.secret=${JWT_SECRET:my-secret-key}

# Configuração de CORS
cors.originPatterns=http://localhost:3000,http://localhost:8080
